pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-backend'){
                    sh '''
                    mkdir -p $WORKSPACE/.go-build $WORKSPACE/.go-mod
                    export GOCACHE=$WORKSPACE/.go-build
                    export GOMODCACHE=$WORKSPACE/.go-mod
                    go test -v ./...
                    '''
                }
            }
        }
    }
}
